In [1]:
# problem 1 

In [ ]:
Python libraries are collections of pre-written code and functions that extend the capabilities of the Python programming language.
Python libraries makes it convenient for the programmer as they wouldn't have to write the same code multiple times for different programs.

In [ ]:
# problem 3

In [4]:
import numpy as np

arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

# Shape of the array
shape = arr.shape

# Size of the array
size = arr.size

# Number of dimensions of the array
dimension = arr.ndim

print("Shape:", shape)
print("Size:", size)
print("Dimension:", dimension)

Shape: (3, 4)
Size: 12
Dimension: 2


In [ ]:
# problem 4

In [5]:
import numpy as np
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
first_row = arr[0]
print("First Row:", first_row)

First Row: [1 2 3 4]


In [ ]:
# problem 5

In [6]:
import numpy as np

arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

element = arr[2, 3]

print("Element at third row and fourth column:", element)

Element at third row and fourth column: 12


In [7]:
# problem 6

In [8]:
import numpy as np
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
odd_indexed_elements = arr[:, 1::2].flatten()
print("Odd-indexed elements:", odd_indexed_elements)

Odd-indexed elements: [ 2  4  6  8 10 12]


In [ ]:
# problem 7

In [9]:
import numpy as np

rand_matrix = np.random.rand(3, 3)

print("Random 3x3 matrix:")
print(rand_matrix)

Random 3x3 matrix:
[[0.1281389  0.63337056 0.94374374]
 [0.77492594 0.17345568 0.9360637 ]
 [0.57951164 0.63307563 0.12727015]]


In [10]:
# problem 9

In [11]:
import numpy as np

arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

# Increase the dimension of the array
new_arr = np.expand_dims(arr, axis=0)

print("Original Array:")
print(arr)
print("Array with increased dimension:")
print(new_arr)

Original Array:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
Array with increased dimension:
[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]]


In [ ]:
# problem 10

In [12]:
import numpy as np

arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

# Transpose the array
transposed_arr = np.transpose(arr)
# Or, you can use arr.T

print("Original Array:")
print(arr)
print("Transposed Array:")
print(transposed_arr)

Original Array:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
Transposed Array:
[[ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]
 [ 4  8 12]]


In [ ]:
# problem 11

In [15]:
import numpy as np

# Define the matrices
A = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
B = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

# Index-wise multiplication
index_wise_multiplication = A * B
print("Index-wise multiplication:")
print(index_wise_multiplication)

Index-wise multiplication:
[[  1   4   9  16]
 [ 25  36  49  64]
 [ 81 100 121 144]]


In [16]:
import numpy as np

# Define the matrices
A = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
B = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
matrix_multiplication = np.dot(A, B.T)  # Assuming you want to multiply A by the transpose of B
print("\nMatrix multiplication:")
print(matrix_multiplication)


Matrix multiplication:
[[ 30  70 110]
 [ 70 174 278]
 [110 278 446]]


In [17]:
import numpy as np

# Define the matrices
A = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
B = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

# Add both matrices
matrix_addition = A + B
print("\nMatrix addition:")
print(matrix_addition)


Matrix addition:
[[ 2  4  6  8]
 [10 12 14 16]
 [18 20 22 24]]


In [18]:
import numpy as np

A = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
B = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

# Subtract matrix B from matrix A
matrix_subtraction = A - B
print("/nMatrix subtraction:")
print(matrix_subtraction)

/nMatrix subtraction:
[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]


In [19]:
import numpy as np

# Define the matrices
A = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
B = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

# Divide matrix B by matrix A
matrix_division = B / A
print("/nMatrix division:")
print(matrix_division)

/nMatrix division:
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [ ]:
# problem 12

In [ ]:
In NumPy, you can use the byteswap method to swap the byte order of an array. This method swaps the endianness of the array elements.

In [ ]:
# problem 15

In [ ]:
Broadcasting in NumPy is a mechanism that allows arrays of different shapes to be combined in arithmetic operations. When operating on two arrays, NumPy compares their shapes element-wise. It starts with the trailing dimensions and works its way backward, aligning dimensions where one of the dimensions is 1. The dimensions are compatible when either they are equal or one of them is 1.